CC=gcc
CFLAGS=-Werror -Wall
SOURCE=main.c ft_putchar.c 

rush00:
	$(CC) $(CFLAGS) -g ${SOURCE} rush00.c  

rush01:
	$(CC) $(CFLAGS) -g ${SOURCE} rush01.c

rush02:
	$(CC) $(CFLAGS) -g ${SOURCE} rush02.c

rush03:
	$(CC) $(CFLAGS) -g ${SOURCE} rush03.c

rush04:
	$(CC) $(CFLAGS) -g ${SOURCE} rush04.c

clean:
	rm -rf *.dSYM *~ *.o a.out

run:
	./a.out
