# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sqian <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/13 12:51:58 by sqian             #+#    #+#              #
#    Updated: 2016/07/13 18:26:47 by sqian            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
CC = gcc
CFLAGS = -Werror -Wall  
TARGET = test
SOURCE1 = ft_print_reverse_alphabet.c
SOURCE2 = test.c

$(TARGET):$(SOURCE)
	$(CC) $(CFLAGS) -g $(SOURCE1) $(SOURCE2) -o $@ 
