# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sqian <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/13 12:56:08 by sqian             #+#    #+#              #
#    Updated: 2016/07/13 20:50:52 by sqian            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc
CFLAGS = -Werror -Wall
TARGET = test
SOURCE1 = ft_print_combn.c
SOURCE2 = test.c
$(TARGET):$(SOURCE)
	$(CC) $(CFLAGS) -g $(SOURCE1) $(SOURCE2) -o $@ 
